server:
  port: 8081

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: scrapper
    password: password
  liquibase:
    enabled: true
    change-log: classpath:migrations/master.xml
  jackson:
    property-naming-strategy: SNAKE_CASE
  grpc:
    server:
      port: 9091
      host: 0.0.0.0
    client:
      bot-service:
        address: "static://localhost:9090"
        negotiation-type: plaintext
  kafka:
    bootstrap-servers: "localhost:29092,localhost:29093,localhost:29094"
    producer:
      acks: all
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: io.confluent.kafka.serializers.KafkaAvroSerializer
    properties:
      schema.registry.url: "http://localhost:8082"
      enable.idempotence: "true"

app:
  client-type: kafka
  database-access-type: orm
  kafka:
    topic-name: "link-updates"
  bot:
    url: "http://localhost:8080"
    grpc-address: "localhost:9090"
  stackoverflow:
    key: ${STACKOVERFLOW_KEY}
    access-token: ${STACKOVERFLOW_ACCESS_KEY}
  github:
    token: ${GITHUB_TOKEN}
  scheduler:
    link-update-delay: 30000
    batch-size: 100
    threads: 4
    offset: 0
  outbox:
    scheduler:
      delay-ms: 5000
      batch-size: 50

logging:
  logging:
    level:
      org.springframework.boot.autoconfigure.liquibase: DEBUG
      liquibase: DEBUG
      org.apache.kafka: WARN
  structured:
    format:
      console: logstash
