server:
  port: 8081

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5432/scrapper
    username: scrapper
    password: password
  liquibase:
    enabled: true
    change-log: classpath:migrations/master.xml
  jackson:
    property-naming-strategy: SNAKE_CASE
  grpc:
    server:
      port: 9091
      host: 0.0.0.0
    client:
      bot-service:
        address: "static://localhost:9090"
        negotiation-type: plaintext

app:
  client-type: grpc
  database-access-type: orm
  bot:
    url: "http://localhost:8080"
    grpc-address: "localhost:9090"
  stackoverflow:
    key: ${STACKOVERFLOW_KEY}
    access-token: ${STACKOVERFLOW_ACCESS_KEY}
  github:
    token: ${GITHUB_TOKEN}
  scheduler:
    link-update-delay: 30000
    batch-size: 100
    threads: 4
    offset: 0

logging:
  logging:
    level:
      org.springframework.boot.autoconfigure.liquibase: DEBUG
      liquibase: DEBUG
  structured:
    format:
      console: logstash
