server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force: true

spring:
  devtools:
    restart:
      enabled: false
  application:
    name: bot
  messages:
    encoding: UTF-8
  grpc:
    server:
      port: 9090
      host: 0.0.0.0
    client:
      channels:
        scrapper-service:
          address: "localhost:9091"
  kafka:
    bootstrap-servers: "localhost:29092,localhost:29093,localhost:29094"
    consumer:
      group-id: "final-v50"
      auto-offset-reset: "earliest"
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: io.confluent.kafka.serializers.KafkaAvroDeserializer
    properties:
      schema.registry.url: "http://localhost:8082"
      specific.avro.reader: "true"

app:
  client-type: kafka
  kafka:
    topic-name: "link-updates"
  scrapper:
    url: "http://localhost:8081"
    grpc-address: "localhost:9091"
  telegram:
    url: https://api.telegram.org/bot
    token: ${TELEGRAM_TOKEN}
    update-listener-sleep: 1s
    debug: false

logging:
  structured:
    format:
      console: logstash
